"""add_conversation_content_and_model_fields_to_projects

Revision ID: 094490142390
Revises: 
Create Date: 2025-11-11 16:08:44.597387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094490142390'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('conversation_content', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('image_model', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('aspect_ratio', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('quality', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'quality')
    op.drop_column('projects', 'aspect_ratio')
    op.drop_column('projects', 'image_model')
    op.drop_column('projects', 'conversation_content')
    # ### end Alembic commands ###

